steps:
  # Step 1: Install dependencies
  - name: node:20
    entrypoint: npm
    args: [install]

  # Step 2: Build TypeScript to JavaScript
  - name: node:20
    entrypoint: npm
    args: [run, build]

  # Step 3: Build Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - asia-northeast1-docker.pkg.dev/$PROJECT_ID/whitepaper-agent/whitepaper-agent:$BUILD_ID
      - -t
      - asia-northeast1-docker.pkg.dev/$PROJECT_ID/whitepaper-agent/whitepaper-agent:latest
      - .

  # Step 4: Push Docker image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - asia-northeast1-docker.pkg.dev/$PROJECT_ID/whitepaper-agent/whitepaper-agent:$BUILD_ID

  # Step 5: Push latest tag
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - asia-northeast1-docker.pkg.dev/$PROJECT_ID/whitepaper-agent/whitepaper-agent:latest

  # Step 6: Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - whitepaper-agent
      - --image=asia-northeast1-docker.pkg.dev/$PROJECT_ID/whitepaper-agent/whitepaper-agent:$BUILD_ID
      - --platform=managed
      - --region=asia-northeast1
      - --allow-unauthenticated
      - --max-instances=10
      - --memory=1Gi
      - --cpu=1
      - --timeout=300
      - --port=8080
      - --set-env-vars=NODE_ENV=production,GCP_PROJECT_ID=$PROJECT_ID
      - --set-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,SESSION_SECRET=SESSION_SECRET:latest,GCS_BUCKET_NAME=GCS_BUCKET_NAME:latest

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s
